<p>Il a été constaté que 18% des accidents de la route étaient dus au mauvais entretien du véhicule.
De ce constat, l'association &laquo;les mécanos du coeur&raquo; a été créée dans le but d'aider les personnes à faible revenu à entretenir leur véhicule, enfin de rouler en toute sécurité.
</p> 


<div class="center">
<iframe frameborder="0" width="480" height="270" src="https://www.dailymotion.com/embed/video/xmzqui" allowfullscreen allow="autoplay"></iframe>
	<br />

	<a
	href="https://www.dailymotion.com/video/xmzqui_les-mecanos-du-coeur-dans-prioriterre_news"
	 onclick="window.open(this.href); return false;" >Les M&eacute;canos du Coeur dans Prioriterre</a> <i>par
	<a href="https://www.dailymotion.com/france3provencealpes"
	 onclick="window.open(this.href); return false;" >france3provencealpes</a></i>

</div>


