<h1>Adhérer à l'association</h1>

<p>L'association &laquo;les mécanos du coeur&raquo; est une association loi
1901. En tant que telle, il suffit de payer une cotisation de 10€ pour y
adhérer (tarif annuel).</p>

<p>Vous pouvez <a href="/Nous-soutenir">soutenir l'association</a>.
Si vous en avez besoin, vous pouvez utiliser les services du garage.</p>

<h1>Le garage</h1>
<p>Les réparations sont principalement ouvertes aux gens les plus démunis. Nous acceptons toutes personnes ayant des difficultés pour entretenir leur véhicule.</p>
<p>Lors de la première intervention sur un véhicule, il est nécessaire d'apporter les documents suivants :</p> 
<ul>
	<li>Permis de conduire</li>
	<li>Carte grise</li>
	<li>Assurance de la voiture</li>
	<li>Dernier avis d'imposition</li>
	<li>Justificatif de la CAF pour les bénéficiaires du RSA</li>
</ul>
<div class="center"><img src="img/garage.jpg" alt="le garage" /></div>
