<p>La voiture est outil indispensable pour la vie professionnelle et sociale. Mais 
pour avoir une voiture, il faut le permis de conduire.  Malheureusement,même
les personnes ayant les capacités, mais ayant des problèmes de français, 
d'illettrisme ...  ne peuvent obtenir ce sésame dans le circuit habituel.</p>

<p>L'auto-école associative est un projet des mécanos du coeur. Son but est de 
pouvoir rendre accessible le permis de conduire à tout le monde.</p>



<h1>Première étape : Obtention du code</h1>

<p>L’association &laquo;les mécanos du coeur&raquo; possède un vidéo projecteur
et des DVD du code Rousseau, des tables et des chaises.  Parfait pour réviser
votre code ou préparer à l'examen théorique du permis de conduire.  Nos
bénévoles prennent le temps d'expliquer le vocabulaire spécifique au code,
permettant aux personnes de surmonter leurs difficultés.</p>



<div class="center"><img src="img/ecole.jpg" alt="photo école"/></div>
<h1>Deuxième étape : Obtention de l'épreuve pratique</h1>

<p>Cette étape reste pour l'instant à l'état de projet.  Comme pour la première
étape, le concept est d'aider les personnes à  vaincre les appréhensions
rencontrées dans leur apprentissage de la conduite.</p>

<p>Mais pour l'instant, il nous manque le financement pour embaucher un
moniteur agréé ou un bénévole ayant cet agrément. Il nous manque aussi une
voiture d'auto-école.  </p>
