<h1>Le principe</h1>

<p> Le garage est ouvert aux adhérents pour faire différentes réparations de
leur véhicule. Ces réparations entrent dans le cadre de l'entretien courant,
telles que les freins, les vidanges, les courroies, etc. Il est possible aussi
de faire d'autres réparations, si le garage possède le matériel et les
compétences nécessaires. <br/>

Notre activité se concentre essentiellement sur la mécanique. Nous ne faisons
pas de carrosserie et que certaines interventions en électricité. <br/>

Veuillez nous contacter au préalable pour un diagnostic et éventuellement un
rendez-vous.  </p>

<p>Généralement, les adhérents achètent eux-mêmes les pièces à changer, chez
des fournisseurs leur faisant des réductions. 
En outre, nous bénéficions de prix très intéressants pour le contrôle technique
dans un Centre Agréé.
</p>

<h1>Réparations par un mécanien diplômé</h1>

<p> Le prix des prestations est de 15€ de l’heure de main d’œuvre pour les
personnes qui perçoivent les minima sociaux, 30€ pour les personnes non
imposables, 40€ pour les personnes imposables. Il existe des forfaits pour les
vidanges, freins , etc. <br/> 

Les propriétaires des voitures peuvent être présents pendant les réparations
pour participer si nécessaire aux travaux. <br/>

Par ailleurs le tarif en auto-réparation varie entre 5€ et 15€ de l'heure
selon l'autonomie de l'adhérent et l'utilisation ou non du pont.  </p>

<h1>Auto-Réparation</h1>

<p> Le garage est ouvert tous les jours aux adhérents qui désirent réparer
eux-mêmes leur véhicule. Ils payent la location du garage et des outils selon
leurs revenus. Cette activité est encadrée par des bénévoles compétents. Ils
donnent de précieux conseils. Le tout dans un climat convivial et d’entraide.
Contactez-nous pour prendre rendez-vous.  </p> 



<div class="center"><img src="img/heureux.jpg" alt="auto reparation"/></div>
