<div class="floatright"><img src="/img/logo300px.jpg" alt="logo" /></div>


<p> Les mécanos du cœur se sont structurés en association 1901. Depuis 19
février 1998, la mission principale de l’association est
d’aider les personnes en difficultés à entretenir et réparer leur voiture,
outil indispensable pour avoir une vie familiale et un emploi.

Elle rassemble à Marseille près de 200 adhérents.  Il
faut être adhérent pour bénéficier des divers services du garage. 

L’association emploie un aide-mécanicien et un responsable d'atelier, tous deux
en contrat d'insertion à 26h / semaine. Des bénévoles assurent l'accueil au
secrétariat.  </p> 


<p> Les échanges non monétaires sont permanents. Il est demandé à tous les
adhérents de l’association de participer activement à la vie associative : à la gestion, à
l’animation et même aux actions collectives du garage (repas, fêtes, cours de
mécanique…). Ainsi les locaux ont été repeints par un adhérent peintre de
métier, les lavabos ont été mis en place par une plombière, etc. Il faut
ajouter une multitude d’échanges de services entre les adhérents eux-mêmes. Le
fonctionnement de l’association est présenté lors du premier accueil.</p>


 <!-- begin VideoJS -->
 <div class="center">
<iframe width="560" height="315" src="https://www.youtube.com/embed/_vmbpwTUVoc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

 <!-- End VideoJS -->

<?php 
