<h1>Comment soutenir l'association ?</h1>
<p>Il existe plusieurs façons de soutenir l'association :</p>
<ul>
	<li>Devenir bénévole</li>
	<li>Faire des dons : outils, huile, différentes pièces, voitures...</li>
</ul>


<h1>Remerciements</h1>

<p>L'association fonctionne grâce aux subventions du Conseil Général, du
Conseil Régional, de la Cress et du FSE.  Elle fonctionne aussi grâce aux
outils et au matériel pédagogique fournis par différents dons de la fondation
Macif, la Caisse d'épargne et Renault...  </p>


<p>Que serait l'association sans ses membres et ses soutiens ? Un
grand merci à eux.</p>
<div class="center"><img src="img/fete.jpg" alt="barbecue" /></div>

<h1 id="partenaires">Nos partenaires</h1>
<div id="logo">
<table>
<tr>
<td><a href="http://www.caisse-epargne.fr" onclick="window.open(this.href); return false;" ><img src="img/sponsors/Caisse_depargne_logo.png" alt="La caisse d'épargne"/></a></td>
<td><a href="http://www.fondation-macif.org/" onclick="window.open(this.href); return false;" ><img src="img/sponsors/macif.png" alt="La fondation Macif"/></a></td>
<td><a href="http://www.regionpaca.fr/" onclick="window.open(this.href); return false;" ><img src="img/sponsors/image2.jpeg" alt="La région PACA"/></a></td>
</tr><tr>
<td><a href="http://www.fse.gouv.fr/" onclick="window.open(this.href); return false;" ><img src="img/sponsors/image1.jpeg" alt="Fond social européenne"/></a></td>
<td><a href="http://www.fse.gouv.fr/" onclick="window.open(this.href); return false;" ><img src="img/sponsors/image3.jpeg" alt="Fond social européenne"/></a></td>
<td><a href="http://www.cresspaca.org/" onclick="window.open(this.href); return false;" ><img src="img/sponsors/logo-cress.gif" alt="Caisse Régionale économie social et solidaire"/></a></td>
</tr><tr>
<td><a href="http://www.renault.fr/" onclick="window.open(this.href); return false;" ><img src="img/sponsors/renault_logo.png" alt="Renault"/></a></td>
<td colspan="2" ><a href="http://www.cg13.fr/" onclick="window.open(this.href); return false;" ><img src="img/sponsors/Logo_13_bouches_du_rhone100.png" alt="Conseil générale des bouches du rhones"/></a></td>
</tr>
</table>
</div>
